### ISSUE TITLE
images are not public anymore

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/vm-images#17]
It appears the images are not public anymore.
I'm getting:
```
Required 'compute.images.useReadOnly' permission for 'projects/cirrus-images'", "errors": [ { "message": "Required 'compute.images.useReadOnly' permission 
when trying to use them to launch a VM in my GCP project.
```

gcloud fails too:
```
➜  ~ gcloud compute images list --project cirrus-images --filter=family=docker-builder
ERROR: (gcloud.compute.images.list) Some requests did not succeed:
 - Required 'compute.images.list' permission for 'projects/cirrus-images'
 ```

**Comment by fkorotkov** [comment]
Are you authenticated within `gcloud`? The images should be available for any authenticated user: https://github.com/cirruslabs/vm-images/blob/06077e85ee45822355246e989cbbd7df1a51bcd8/.cirrus.yml#L22

**Comment by geekflyer** [comment]
I am.
I also can't see the images in the GCP console:
https://console.cloud.google.com/compute/images?tab=images&project=cirrus-images

<img width="777" alt="image" src="https://github.com/cirruslabs/vm-images/assets/1221897/bfda392c-a884-4fcb-9bb6-3ee0fd7bb95c">

It's possible that the compute.image.list permission is just not granted and I need to use specific image names, but is there somewhere a good list?

**Comment by geekflyer** [comment]
ok, it turns out I was using:

```
gce_instance:
  image_project: cirrus-images
  image: family/docker-builder
```
but correct one is:
```
gce_instance:
  image_project: cirrus-images
  image_family: docker-builder
```

What was the 
```
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm 
```
syntax for again (compared gce_instance)? Which one is the preferred syntax?

**Comment by fkorotkov** [comment]
Oh! The reason is that `gce_instance` doesn't have `image` field. Only `image_name` and `image_family`. A little bit of inconsistency with the managed instances like `compute_engine_instance` and `freebsd_instance` where it's only `image`.

**Comment by geekflyer** [comment]
ah so `compute_engine_instance` is for managed GCP VMs run by cirrus labs vs `gce_instance` is for self-hosted?

**Comment by fkorotkov** [comment]
Yeah. `gce_instance` runs on your compute where `compute_engine_instance` runs on our and uses compute credits for private repositories.
